categories:
  - title: "Breaking Changes"
    labels:
      - "BC-break"
  - title: "Major Features"
    labels:
      - "MAJOR"
  - title: "Documentation enhancements"
    labels:
      - "Documentation :books:"
template: |
  ## What’s Changed

  $CHANGES
