<?php

declare(strict_types=1);

namespace Atk4\Data\Persistence\Sql;

use Atk4\Data\Exception as BaseException;

/**
 * All exceptions generated by DSQL use this class.
 */
class Exception extends BaseException
{
}
